#!/bin/bash
relay=$(mullvad relay list | sed -e 's/^[\t]\+//' | grep -E "^[a-z0-9\-]+wg-[0-9]+" | cut -d ' ' -f 1 | shuf -n 1)
mullvad relay set location $relay > /dev/null
mullvad connect
sleep 1
mullvad status
